---
apiVersion: v1
kind: ServiceAccount
metadata:
  labels:
    app.kubernetes.io/name: citrix-webhook
    app.kubernetes.io/version: 0.1.1
  name: citrix-webhook
  namespace: cert-manager

---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: citrix-webhook
    app.kubernetes.io/version: 0.1.1
  name: citrix-webhook
rules:
  - apiGroups:
      - ""
    resources:
      - secrets
    verbs:
      - get

---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  labels:
    app.kubernetes.io/name: citrix-webhook
    app.kubernetes.io/version: 0.1.1
  name: citrix-webhook
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: citrix-webhook
subjects:
  - kind: ServiceAccount
    name: citrix-webhook
    namespace: cert-manager

---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  labels:
    app.kubernetes.io/name: citrix-webhook
    app.kubernetes.io/version: 0.1.1
  name: citrix-webhook:webhook-authentication-reader
  namespace: kube-system
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: extension-apiserver-authentication-reader
subjects:
- kind: ServiceAccount
  name: citrix-webhook
  namespace: cert-manager

---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: citrix-webhook
    app.kubernetes.io/version: 0.1.1
  name: citrix-webhook:domain-solver
rules:
- apiGroups:
  - acme.sanaldiyar.com
  resources:
  - '*'
  verbs:
  - create

---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  labels:
    app.kubernetes.io/name: citrix-webhook
    app.kubernetes.io/version: 0.1.1
  name: citrix-webhook:auth-delegator
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: system:auth-delegator
subjects:
- kind: ServiceAccount
  name: citrix-webhook
  namespace: cert-manager

---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  labels:
    app.kubernetes.io/name: citrix-webhook
    app.kubernetes.io/version: 0.1.1
  name: citrix-webhook:domain-solver
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: citrix-webhook:domain-solver
subjects:
- kind: ServiceAccount
  name: cert-manager
  namespace: cert-manager
---
# Grant cert-manager-webhook-citrix permission to read the flow control mechanism (APF)
# API Priority and Fairness is enabled by default in Kubernetes 1.20
# https://kubernetes.io/docs/concepts/cluster-administration/flow-control/
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: citrix-webhook:flowcontrol-solver
  labels:
    app.kubernetes.io/name: citrix-webhook
    app.kubernetes.io/version: 0.1.1
rules:
  - apiGroups:
      - "flowcontrol.apiserver.k8s.io"
    resources:
      - "prioritylevelconfigurations"
      - "flowschemas"
    verbs:
      - "list"
      - "watch"
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: citrix-webhook:flowcontrol-solver
  labels:
    app.kubernetes.io/name: citrix-webhook
    app.kubernetes.io/version: 0.1.1
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: citrix-webhook:flowcontrol-solver
subjects:
  - apiGroup: ""
    kind: ServiceAccount
    name: citrix-webhook
    namespace: cert-manager
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app.kubernetes.io/name: citrix-webhook
    app.kubernetes.io/version: 0.1.1
  name: citrix-webhook
  namespace: cert-manager
spec:
  ports:
  - name: https
    port: 443
    protocol: TCP
    targetPort: https
  selector:
    app.kubernetes.io/name: citrix-webhook
  sessionAffinity: None
  type: ClusterIP
---
apiVersion: cert-manager.io/v1
kind: Issuer
metadata:
  labels:
    app.kubernetes.io/name: citrix-webhook
    app.kubernetes.io/version: 0.1.1
  name: citrix-webhook-ca
  namespace: cert-manager
spec:
  ca:
    secretName: citrix-webhook-ca

---
apiVersion: cert-manager.io/v1
kind: Issuer
metadata:
  labels:
    app.kubernetes.io/name: citrix-webhook
    app.kubernetes.io/version: 0.1.1
  name: citrix-webhook-selfsign
  namespace: cert-manager
spec:
  selfSigned: {}

---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  labels:
    app.kubernetes.io/name: citrix-webhook
    app.kubernetes.io/version: 0.1.1
  name: citrix-webhook-ca
  namespace: cert-manager
spec:
  commonName: ca.citrix-webhook.cert-manager
  duration: 43800h0m0s
  isCA: true
  issuerRef:
    name: citrix-webhook-selfsign
  secretName: citrix-webhook-ca

---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  labels:
    app.kubernetes.io/name: citrix-webhook
    app.kubernetes.io/version: 0.1.1
  name: citrix-webhook-webhook-tls
  namespace: cert-manager
spec:
  dnsNames:
  - citrix-webhook
  - citrix-webhook.cert-manager
  - citrix-webhook.cert-manager.svc
  duration: 8760h0m0s
  issuerRef:
    name: citrix-webhook-ca
  secretName: citrix-webhook-webhook-tls
---
apiVersion: v1
kind: Secret
metadata:
  labels:
    app.kubernetes.io/name: citrix-webhook
    app.kubernetes.io/version: 0.1.1
  name: citrix-webhook-configs
  namespace: cert-manager
type: Opaque
stringData:
  NS_URL: "http://ctrix-adc-url"
  NS_LOGIN: Login
  NS_PASSWORD: Password
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app.kubernetes.io/name: citrix-webhook
    app.kubernetes.io/version: 0.1.1
  name: citrix-webhook
  namespace: cert-manager
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app.kubernetes.io/name: citrix-webhook
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      creationTimestamp: null
      labels:
        app.kubernetes.io/instance: citrix-webhook
        app.kubernetes.io/name: citrix-webhook
    spec:
      containers:
      - args:
        - --tls-cert-file=/tls/tls.crt
        - --tls-private-key-file=/tls/tls.key
        envFrom:
        - secretRef:
            name: citrix-webhook-configs
        env:
        - name: GROUP_NAME
          value: acme.sanaldiyar.com
        image: docker.io/kazimsarikaya/citrixadccertmanagerwebhook:latest
        imagePullPolicy: Always
        livenessProbe:
          failureThreshold: 3
          httpGet:
            path: /healthz
            port: https
            scheme: HTTPS
          periodSeconds: 10
          successThreshold: 1
          timeoutSeconds: 1
        name: citrix-webhook
        ports:
        - containerPort: 443
          name: https
          protocol: TCP
        readinessProbe:
          failureThreshold: 3
          httpGet:
            path: /healthz
            port: https
            scheme: HTTPS
          periodSeconds: 10
          successThreshold: 1
          timeoutSeconds: 1
        resources: {}
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
        volumeMounts:
        - mountPath: /tls
          name: certs
          readOnly: true
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      serviceAccount: citrix-webhook
      serviceAccountName: citrix-webhook
      terminationGracePeriodSeconds: 30
      volumes:
      - name: certs
        secret:
          defaultMode: 420
          secretName: citrix-webhook-webhook-tls

---
apiVersion: apiregistration.k8s.io/v1
kind: APIService
metadata:
  annotations:
    cert-manager.io/inject-ca-from: cert-manager/citrix-webhook-webhook-tls
  labels:
    app.kubernetes.io/name: citrix-webhook
    app.kubernetes.io/version: 0.1.1
  name: v1alpha1.acme.sanaldiyar.com
spec:
  group: acme.sanaldiyar.com
  groupPriorityMinimum: 1000
  service:
    name: citrix-webhook
    namespace: cert-manager
  version: v1alpha1
  versionPriority: 15
